name: Sync GitHub → Azure DevOps (Per-Branch Sync, Preserve Azure Files ✅)

on:
  push:
    branches:
      - '*'  # ✅ Trigger on push to any branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ Fetch all history and branches

      - name: Set up Git
        run: |
          git config --global user.email "sync@github.com"
          git config --global user.name "GitHub Actions Sync"

      - name: Sync current branch to Azure DevOps (Preserve Azure Files)
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          AZURE_DEVOPS_ORG: ${{ secrets.AZURE_DEVOPS_ORG }}
          AZURE_DEVOPS_PROJECT: ${{ secrets.AZURE_DEVOPS_PROJECT }}
          AZURE_DEVOPS_REPO: ${{ secrets.AZURE_DEVOPS_REPO }}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Syncing current branch: $CURRENT_BRANCH"

          # Azure DevOps repo URL with PAT
          AZURE_REPO_URL="https://$AZURE_DEVOPS_PAT@dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_git/$AZURE_DEVOPS_REPO"

          # Clone Azure DevOps repo
          git clone $AZURE_REPO_URL azure_repo
          cd azure_repo

          # Checkout or create the branch in Azure DevOps repo
          git checkout -B "$CURRENT_BRANCH" origin/"$CURRENT_BRANCH" 2>/dev/null || git checkout -b "$CURRENT_BRANCH"

          # Add GitHub repo as remote
          git remote add github https://github.com/${{ github.repository }}.git
          git fetch github

          # Merge GitHub branch into Azure DevOps branch, preserving Azure-only files
          git merge --strategy=recursive --strategy-option=theirs "github/$CURRENT_BRANCH" --no-edit || true

          # Commit if there are any changes
          git add .
          git commit -m "Sync from GitHub branch $CURRENT_BRANCH (preserve Azure-only files)" || true

          # Push only current branch
          git push origin "$CURRENT_BRANCH"

          # Cleanup
          cd ..
          rm -rf azure_repo
